services:
    ecyaz.postlengthreminder.listener:
        class: ecyaz\postlengthreminder\event\listener
        arguments:
            - '@config'
            - '@language'
        tags:
            - { name: event.listener }
